name: Notificar Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Novo commit enviado!"
